version: '2'
services:
  rs1_node1:
    image: mongo:4.2
    command: mongod --keyFile /opt/mongodb-keyfile --oplogSize 10240 --replSet rs1 --port 27017 
    volumes:
      - /home/docker/mongodb-test/data1:/data/db
      - /home/docker/mongodb-test/mongodb-keyfile:/opt/mongodb-keyfile
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "22217:27017"
    restart:
      always
    container_name:
      mongo-rs1-node1-test
    ulimits:
      nofile:
        soft: 300000
        hard: 300000
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mc-MG-2020-PWD-test
    mem_limit: 2g
  rs1_node2:
    image: mongo:4.2
    command: mongod --keyFile /opt/mongodb-keyfile --oplogSize 10240 --replSet rs1 --port 27017
    volumes:
      - /home/docker/mongodb-test/data2:/data/db
      - /home/docker/mongodb-test/mongodb-keyfile:/opt/mongodb-keyfile
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "22218:27017"
    restart:
      always
    container_name:
      mongo-rs1-node2-test
    ulimits:
      nofile:
        soft: 300000
        hard: 300000
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mc-MG-2020-PWD-test
    mem_limit: 2g
